exports.seed = (knex) => {
  // Deletes ALL existing entries
  return knex('case').del()
    .then(() => {
      // Inserts seed entries
      return knex('case').insert([
        { id: 1, name: 'Cooler Master', model: 'NR200P', formFactor: 'Micro Tower', mbSupport: 'Mini-Itx', cpuCooler: '155mm', psu: 'SFX', expansionSlots: 3, fiveDriveMax: 0, threeDriveMax: 2, twoDriveMax: 3, topFanMax: 2, topFanSize: '120mm', frontFanMax: 0, frontFanSize: '', rearFanMax: 1, rearFanSize: '92mm', bottomFanMax: 2, bottomFanSize: '120mm', sideFanMax: 2, sideFanSize: '120/140mm', rearRadSize: '92mm', topRadSize: '', bottomRadSize: '120/240mm', sideRadSize: '120/140/240/280mm', frontRadSize: '', psuMaxSize: '130mm', gpuMaxH: '156mm', gpuMaxL: '330mm', gpuMaxW: '60mm' },
        { id: 2, name: 'Metallic Gear', model: 'Neo G', formFactor: 'Micro Tower', mbSupport: 'Mini-Itx', cpuCooler: '160mm', psu: 'SFX', expansionSlots: 2, fiveDriveMax: 0, threeDriveMax: 1, twoDriveMax: 2, topFanMax: 0, topFanSize: '', frontFanMax: 2, frontFanSize: '120/140mm', rearFanMax: 0, rearFanSize: '', bottomFanMax: 0, bottomFanSize: '', sideFanMax: 2, sideFanSize: '120mm', rearRadSize: '', topRadSize: '', bottomRadSize: '', sideRadSize: '240mm', frontRadSize: '240/280mm', psuMaxSize: '190mm', gpuMaxH: '156mm', gpuMaxL: '345mm', gpuMaxW: '60mm' },
        { id: 3, name: 'NZXT', model: 'H510 Elite', formFactor: 'Mid Tower', mbSupport: 'Mini-Itx/Micro-Atx/Atx', cpuCooler: '165mm', psu: 'ATX', expansionSlots: 7, fiveDriveMax: 0, threeDriveMax: 3, twoDriveMax: 3, topFanMax: 1, topFanSize: '120/140mm', frontFanMax: 2, frontFanSize: '120/140mm', rearFanMax: 1, rearFanSize: '120mm', bottomFanMax: 0, bottomFanSize: '', sideFanMax: 0, sideFanSize: '', rearRadSize: '120mm', topRadSize: '', bottomRadSize: '', sideRadSize: '', frontRadSize: 'Two 120/140mm', psuMaxSize: '190mm', gpuMaxH: '156mm', gpuMaxL: '381mm', gpuMaxW: '60mm' },
        { id: 4, name: 'Phanteks', model: 'Eclipse P500', formFactor: 'Mid Tower', mbSupport: 'E-Atx/Atx/Micro-Atx/Mini-Itx', cpuCooler: '190mm', psu: 'ATX', expansionSlots: 10, fiveDriveMax: 0, threeDriveMax: 10, twoDriveMax: 3, topFanMax: 3, topFanSize: '120/140mm', frontFanMax: 3, frontFanSize: '120/140mm', rearFanMax: 1, rearFanSize: '120/140mm', bottomFanMax: 0, bottomFanSize: '', sideFanMax: 0, sideFanSize: '', rearRadSize: '120/140mm', topRadSize: '280/360mm', bottomRadSize: '', sideRadSize: '', frontRadSize: '360/420mm', psuMaxSize: '250mm', gpuMaxH: '156mm', gpuMaxL: '435mm', gpuMaxW: '60mm' },
        { id: 5, name: 'Lian Li', model: 'Pc-011d', formFactor: 'Full Tower', mbSupport: 'E-Atx/Atx/Micro-Atx/Mini-Itx', cpuCooler: '167mm', psu: 'ATX', expansionSlots: 10, fiveDriveMax: 0, threeDriveMax: 10, twoDriveMax: 6, topFanMax: 3, topFanSize: '120/140mm', frontFanMax: 0, frontFanSize: '', rearFanMax: 1, rearFanSize: '120', bottomFanMax: 2, bottomFanSize: '140mm', sideFanMax: 3, sideFanSize: '120mm', rearRadSize: '120', topRadSize: '280/360mm', bottomRadSize: '280/360mm', sideRadSize: '360mm', frontRadSize: '', psuMaxSize: '280mm', gpuMaxH: '156mm', gpuMaxL: '446mm', gpuMaxW: '60mm' },
        { id: 6, name: 'Phanteks', model: 'Enthoo 719', formFactor: 'Full Tower', mbSupport: 'E-Atx/Atx/Micro-Atx/Mini-Itx', cpuCooler: '195mm', psu: 'ATX', expansionSlots: 11, fiveDriveMax: 0, threeDriveMax: 16, twoDriveMax: 11, topFanMax: 3, topFanSize: '120/140mm', frontFanMax: 4, frontFanSize: '120/140mm', rearFanMax: 1, rearFanSize: '120/140', bottomFanMax: 3, bottomFanSize: '120/140mm', sideFanMax: 4, sideFanSize: '120mm', rearRadSize: '120/140mm', topRadSize: '360mm', bottomRadSize: '360mm', sideRadSize: '480mm', frontRadSize: '480mm', psuMaxSize: '280mm', gpuMaxH: '156mm', gpuMaxL: '503mm', gpuMaxW: '60mm' }
      ])
    })
}
